### ISSUE TITLE
Can you fix EggWars Plugin by GamakCZ? if you can please tell me to tell you what is the crash !

### ISSUE THREAD

**Issue by XFIREGANER** [Hyroxing/LobbySystem#1]

**Comment by georgianYT** [comment]
Credits for Pocketmine-PHp

**Comment by XFIREGANER** [comment]
@georgianYT 

can you fix it?

**Comment by GamerDaniel3000** [comment]
@XFIREGANER we only make our own plugins....

**Comment by XFIREGANER** [comment]
@GamerDaniel3000

ok make the plugin...

**Comment by TobiasDevDE** [comment]
You can add ideas at our discord with :suggest command!

**Comment by XFIREGANER** [comment]
I don't have Discord😢😢😢😢

**Comment by treehousemc1** [comment]
theres nothing wrong in gamakck eggwars im using it and its working good

**Comment by XFIREGANER** [comment]
no it is crash
1-if you quit from server and join you aren't leaving from arena

**Comment by XFIREGANER** [comment]
no it is crash
1-if you quit from server and join you aren't leaving from arena

**Comment by TobiasDevDE** [comment]
I will close this issue beceause it's not related with the LobbySystem / the Repo. XFIREGANER, i recommend you to ask for help at http://poggit.pmmp.io

**Comment by ByxNilsGFXx** [comment]
LobbySystem eh GEDOWNLOADET

**Comment by iTzFreeHD** [comment]
Nein ist es nicht oder hast du irgendwo anders genau das schonmal gesehen?

**Comment by TobiasDevDE** [comment]
@RushEnte Hast du Twitter o.ä. wo wir mal schreiben könnten?
