### ISSUE TITLE
Why do you put my plugin organization 

### ISSUE THREAD

**Issue by georgianYT** [Hyroxing/LobbySystem#2]

**Comment by GamerDaniel3000** [comment]
@georgianYT what plugin?

**Comment by iTzFreeHD** [comment]
Please teel us wich Plugin is yours at this Organization?

**Comment by TobiasDevDE** [comment]
Closed due to inactivity by the Author...

**Comment by zBearchenPlayz** [comment]
No

**Comment by zBearchenPlayz** [comment]
War ja klar,sieht man das ihr nicht Downloadet?

**Comment by ByxNilsGFXx** [comment]
Scheiss downloader

**Comment by iTzFreeHD** [comment]
Wo wurde hier etwas runtergeldaden?!

**Comment by TobiasDevDE** [comment]
@zBearchenPlayz Bitte äußere dich mal zu dem oben geschriebenen. Sämtliche Plugins auf diesem Github-Account sind selbstprogrammiert, und zwar zu 100%. Bitte nenne uns einige Belege, wieso dies nicht so ist, oder lass es.
